apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.adService.name }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.adService.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.adService.name }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: {{ .Values.images.repository }}/{{ .Values.adService.name }}:{{ .Values.images.tag | default .Chart.AppVersion }}
        ports:
        - containerPort: {{ .Values.adService.port | default 9555 }}
        env:
        - name: PORT
          value: "{{ .Values.adService.port | default 9555 }}"
        resources:
          {{- toYaml .Values.adService.resources | nindent 10 }}
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 15
          grpc:
            port: {{ .Values.adService.port | default 9555 }}
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 15
          grpc:
            port: {{ .Values.adService.port | default 9555 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.adService.name }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.adService.serviceType | default "ClusterIP" }}
  selector:
    app: {{ .Values.adService.name }}
    release: {{ .Release.Name }}
  ports:
  - name: grpc
    port: {{ .Values.adService.port | default 9555 }}
    targetPort: {{ .Values.adService.port | default 9555 }}
