apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.checkoutService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.checkoutService.name }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.checkoutService.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.checkoutService.name }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: {{ .Values.images.repository }}/{{ .Values.checkoutService.name }}:{{ .Values.images.tag | default .Chart.AppVersion }}
          ports:
            - containerPort: 5050
          readinessProbe:
            grpc:
              port: 5050
          livenessProbe:
            grpc:
              port: 5050
          env:
            - name: PORT
              value: "5050"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "{{ .Values.checkoutService.services.productCatalogService.port }}"
            - name: SHIPPING_SERVICE_ADDR
              value: "{{ .Values.checkoutService.services.shippingService.port }}"
            - name: PAYMENT_SERVICE_ADDR
              value: "{{ .Values.checkoutService.services.paymentService.port }}"
            - name: EMAIL_SERVICE_ADDR
              value: "{{ .Values.checkoutService.services.emailService.port }}"
            - name: CURRENCY_SERVICE_ADDR
              value: "{{ .Values.checkoutService.services.currencyService.port }}"
            - name: CART_SERVICE_ADDR
              value: "{{ .Values.checkoutService.services.cartService.port }}"
          resources:
            {{- toYaml .Values.checkoutService.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.checkoutService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.checkoutService.name }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.checkoutService.name }}
    release: {{ .Release.Name }}
  ports:
    - name: grpc
      port: 5050
      targetPort: 5050
