apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.currencyService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.currencyService.name }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.currencyService.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.currencyService.name }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: {{ .Values.images.repository }}/{{ .Values.currencyService.name }}:{{ .Values.images.tag | default .Chart.AppVersion }}
        ports:
        - name: grpc
          containerPort: {{ .Values.currencyService.port }}
        env:
        - name: PORT
          value: "{{ .Values.currencyService.port }}"
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"          
        readinessProbe:
          grpc:
            port: {{ .Values.currencyService.port }}
        livenessProbe:
          grpc:
            port: {{ .Values.currencyService.port }}
        resources:
          {{- toYaml .Values.currencyService.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.currencyService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.currencyService.name }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.currencyService.name }}
    release: {{ .Release.Name }}
  ports:
  - name: grpc
    port: {{ .Values.currencyService.port }}
    targetPort: {{ .Values.currencyService.port }}
